// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_rest_controller.Data;

#nullable disable

namespace api_rest_controller.Migrations;

[DbContext(typeof(ApiContext))]
partial class ApiContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("api_rest_controller.Models.Customer", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("Age")
                    .HasColumnType("int");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Customers");
            });
#pragma warning restore 612, 618
    }
}
